使用KNN进行回归预测

In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV

pandas读取数据

In [2]:
data = pd.read_csv('./train.csv')
X = data.T
X = X[1:385]
X = X.T
Y = data['reference']

In [3]:
tdata = pd.read_csv('./test.csv')
pre_X = tdata.T
pre_X = pre_X[1:385]
pre_X = pre_X.T

声明KNN的回归器

In [11]:
knn = neighbors.KNeighborsRegressor(n_neighbors=2, n_jobs=24)

进行拟合预测

In [12]:
knn.fit(X,Y)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=24, n_neighbors=2, p=2,
          weights='uniform')

In [13]:
pre_Y = knn.predict(pre_X)

In [14]:
id_ = np.array(range(0, 25000))
result = pd.DataFrame({'id':id_,
                      'reference':pre_Y})
result

          id  reference
0          0  28.546070
1          1  21.880687
2          2  69.043072
3          3  54.849484
4          4  53.649074
5          5  68.269647
6          6  46.461422
7          7  89.284111
8          8  23.267567
9          9  51.591040
10        10  35.732105
11        11  68.637996
12        12  56.051172
13        13  32.780130
14        14  26.919086
15        15  16.003520
16        16  37.242081
17        17  44.043935
18        18  23.168322
19        19  94.135171
20        20  47.262506
21        21  78.434697
22        22  56.524392
23        23  26.426575
24        24  55.310326
25        25  31.860130
26        26  36.283452
27        27  84.751772
28        28  40.448828
29        29  15.224062
...      ...        ...
24970  24970  63.451780
24971  24971  47.681596
24972  24972  46.055737
24973  24973  31.286156
24974  24974  45.729628
24975  24975  24.937586
24976  24976  53.754775
24977  24977  35.975966
24978  24978  62.090524
24979  24979  55.000064
24980  24980  71.610191
24981  24981  37.451982
24982  24982  44.768234
24983  24983  35.525714
24984  24984  65.902955
24985  24985  39.189884
24986  24986  34.681733
24987  24987  63.909573
24988  24988  28.072857
24989  24989  30.795516
24990  24990  38.587317
24991  24991  64.555188
24992  24992  41.875840
24993  24993  82.597423
24994  24994  25.235345
24995  24995  32.299710
24996  24996  54.462044
24997  24997  20.641337
24998  24998  67.759477
24999  24999  42.781188

[25000 rows x 2 columns]

In [15]:
result.to_csv('result.csv', index = False)

下面是利用GridSearchCV进行调参的过程

In [6]:
optimized_GBM = GridSearchCV(estimator=knn, param_grid=cv_params, scoring='r2', cv=5, verbose=1, n_jobs=24)
optimized_GBM.fit(X, Y)
evalute_result = optimized_GBM.grid_scores_
print('每轮迭代运行结果:{0}'.format(evalute_result))
print('参数的最佳取值：{0}'.format(optimized_GBM.best_params_))
print('最佳模型得分:{0}'.format(optimized_GBM.best_score_))

Fitting 5 folds for each of 2 candidates, totalling 10 fits

[Parallel(n_jobs=24)]: Done   7 out of  10 | elapsed:  2.5min remaining:  1.1min
[Parallel(n_jobs=24)]: Done  10 out of  10 | elapsed:  3.3min finished

每轮迭代运行结果:[mean: 0.99947, std: 0.00065, params: {'n_neighbors': 1}, mean: 0.99946, std: 0.00064, params: {'n_neighbors': 2}]
参数的最佳取值：{'n_neighbors': 1}
最佳模型得分:0.9994682203

/usr/local/lib/python2.7/dist-packages/sklearn/model_selection/_search.py:761: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)